<?php
/**
 * Copyright (c) 2017 H&O E-commerce specialisten B.V. (http://www.h-o.nl/)
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/** @var $block \Paazl\Shipping\Block\Form\Renderer\Date */
?>
<?php
$fieldCssClass = 'field date field-' . $block->getHtmlId();
$fieldCssClass .= $block->isRequired() ? ' required' : '';
?>
<div class="<?php /* @escapeNotVerified */ echo $fieldCssClass; ?>">
    <label class="label" for="<?php echo $block->getHtmlId()?>"><span><?php /* @escapeNotVerified */ echo $block->getLabel() ?></span></label>
    <div class="control customer-dob">
        <?php echo $block->getFieldHtml(); ?>
        <?php if ($_message = $block->getAdditionalDescription()) : ?>
        <div class="note"><?php /* @escapeNotVerified */ echo $_message; ?></div>
        <?php endif; ?>
    </div>
</div>
